---

- name: TEST
  hosts: all
  connection: network_cli
  gather_facts: no
  
  tasks:
  
  - debug:
      var: hostvars
  
  - name: Execute "show version" CLI command
    nokia.srlinux.cli:
      commands:
        - show version
    register: output
    
  - debug:
      var: output
          
