---

- name: Gather Device Data
  hosts: all
  gather_facts: no
  
  tasks:
  
  - name: Execute "show version" CLI command
    nokia.srlinux.cli:
      commands:
        - show version
    register: output
    
  - debug:
      var: output
          
