---

- name: TEST
  hosts: all
  gather_facts: no
  
  tasks:
  
  - debug:
      var: hostvars
  
  - name: Execute "show version" CLI command
    nokia.srlinux.cli:
      commands:
        - show version
    register: output
    ignore_errors: yes
    
  - debug:
      var: output
      
  - debug:
      msg: "TEST"
          
